services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Haslo12345
    ports:
      - "1434:1433"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "Haslo12345" -C -Q "SELECT 1" || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  thekittysaver.adoptionsystem.api:
    image: thekittysaver.adoptionsystem.api
    build:
      context: .
      dockerfile: src/AdoptionSystem/TheKittySaver.AdoptionSystem.API/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=local
      - ConnectionStringSettings__Database=Server=sqlserver,1433;Database=TheKittySaver;User Id=sa;Password=Haslo12345;TrustServerCertificate=True
    depends_on:
      sqlserver:
        condition: service_healthy

  thekittysaver.frontend:
    image: thekittysaver.frontend
    build:
      context: .
      dockerfile: src/Frontend/TheKittySaver.Frontend/Dockerfile
    ports:
      - "5001:8080"