services:
  thekittysaver.adoptionsystem.slices:
    image: thekittysaver.adoptionsystem.slices
    build:
      context: .
      dockerfile: src/BoundedContexts/AdoptionSystem/TheKittySaver.AdoptionSystem.Slices/Dockerfile

